# Optimizers configuration

  RND:
    enabled: False
    description: Random
    type: low
    optimizer: RND
    initial_sample: False
    lb: null
    ub: null
  SHC:
    enabled: False
    description: Stochastic Hill Climbing
    type: low
    optimizer: SHC
    initial_sample: False
    lb: null
    ub: null
  SA:
    enabled: False
    description: Simulated Annealing
    type: low
    optimizer: SA
    initial_sample: True
    lb: null
    ub: null
  DE:
    enabled: False
    description: Differential Evolution (Inspyred)
    type: low
    optimizer: DEA
    initial_sample: False
    lb: 0
    ub: 4
  ES:
    enabled: True
    description: Evoluation Strategy
    type: low
    optimizer: ES
    generator: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA:
    enabled: False
    description: Genetic algorithm with parent selection, mutation, elitism
    type: low
    optimizer: GA
    initial_sample: False
    lb: null
    ub: null
  PSO:
    enabled: False
    description: Particle swarm
    type: low
    optimizer: PSO
    generator: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA-HH:
    enabled: False
    description: Hyper heuristics
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - PSO
        - GA
    low_level_budget_base: 100
    low_level_sample_runs: 3

