# Optimizers configuration

  SA:
    enabled: True
    description: Simulated Annealing
    type: low
    optimizer: SA
    initial_sample: True
    lb: null
    ub: null
  DE:
    enabled: True
    description: Differential Evolution (Inspyred)
    type: low
    optimizer: DEA
    initial_sample: False
    lb: 0
    ub: 4
  ES:
    enabled: True
    description: Evoluation Strategy (Inspyred)
    type: low
    optimizer: ES
    generator: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA:
    enabled: True
    description: Genetic algorithm with parent selection, mutation, elitism
    type: low
    optimizer: GA
    generator: chromosome
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
  PSO:
    enabled: true
    description: Particle swarm
    type: low
    optimizer: PSO
    generator: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA-HH:
    enabled: False
    description: Hyper heuristics
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - PSO
        - GA
    low_level_budget_base: 100
    low_level_sample_runs: 3

