# Optimizers configuration

  SA-N-EA:
    enabled: True
    description: Simulated Annealing with exchange adjacent variator
    type: low
    optimizer: SA
    generator_comb: discrete
    generator_cont: continuous
    variator: n_exchange_adjacent
    initial_sample: True
    lb: null
    ub: null
    reheat: False
  SA-N-E:
    enabled: True
    description: Simulated Annealing with exchange variator
    type: low
    optimizer: SA
    generator_comb: discrete
    generator_cont: continuous
    variator: n_exchange
    initial_sample: True
    lb: null
    ub: null
    reheat: False
  SA-N-RI:
    enabled: False
    description: Simulated Annealing with remove-insert variator
    type: low
    optimizer: SA
    generator_comb: discrete
    generator_cont: continuous
    variator: n_remove_insert
    initial_sample: True
    lb: null
    ub: null
    reheat: False
  SA-N-TF:
    enabled: False
    description: Simulated Annealing with n to first variator
    type: low
    optimizer: SA
    generator_comb: discrete
    generator_cont: continuous
    variator: n_to_first
    initial_sample: True
    lb: null
    ub: null
    reheat: False
  DE:
    enabled: True
    description: Differential Evolution (Inspyred)
    type: low
    optimizer: DEA
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  ES:
    enabled: True
    description: Evoluation Strategy (Inspyred)
    type: low
    optimizer: ES
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA-N-EA-1P:
    enabled: False
    description: Genetic algorithm with exchange adjacent variator and one-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange_adjacent
    crossover: one_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-EA-2P:
    enabled: False
    description: Genetic algorithm exchange adjacent variator and two-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange_adjacent
    crossover: two_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-EA-SBOX:
    enabled: True
    description: Genetic algorithm with exchange adjacent variator and sbox crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange_adjacent
    crossover: sbox
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-E-1P:
    enabled: True
    description: Genetic algorithm with exchange variator and one-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange
    crossover: one_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-E-2P:
    enabled: False
    description: Genetic algorithm with exchange variator and two-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange
    crossover: two_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-E-SBOX:
    enabled: False
    description: Genetic algorithm with exchange variator and sbox crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange
    crossover: sbox
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-RI-1P:
    enabled: False
    description: Genetic algorithm with remove-insert variator and one-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_remove_insert
    crossover: one_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-RI-2P:
    enabled: False
    description: Genetic algorithm with remove-insert variator and two-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_remove_insert
    crossover: two_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-RI-SBOX:
    enabled: False
    description: Genetic algorithm with remove-insert variator and sbox crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_remove_insert
    crossover: sbox
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-TF-1P:
    enabled: False
    description: Genetic algorithm with n to first variator and one-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_to_first
    crossover: one_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-TF-2P:
    enabled: False
    description: Genetic algorithm with n to first variator and two-point crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_to_first
    crossover: two_point
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  GA-N-TF-SBOX:
    enabled: False
    description: Genetic algorithm with n to first variator and sbox crossover
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_to_first
    crossover: sbox
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  PSO:
    enabled: True
    description: Particle Swarm Optimization
    type: low
    optimizer: PSO
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  HH-SA-ALL:
    enabled: True
    description: Hyper heuristics - All SA Variants
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - SA-N-EA
        - SA-N-E
        - SA-N-RI
        - SA-N-TF
    decay: 0.8
    decay_coeff: 0.99
    llh_sample_runs: 3
    llh_sample_budget_coeff:  0.01
    llh_budget_coeff: 0.05
  HH-DE-ES:
    enabled: True
    description: Hyper heuristics - DE & ES
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - DE
        - ES
    decay: 0.8
    decay_coeff: 0.99
    llh_sample_runs: 3
    llh_sample_budget_coeff:  0.01
    llh_budget_coeff: 0.05
  HH-GA-ALL:
    enabled: False
    description: Hyper heuristics - All GA Variants
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - GA-N-EA-1P
        - GA-N-EA-2P
        - GA-N-EA-SBOX
        - GA-N-E-1P
        - GA-N-E-2P
        - GA-N-E-SBOX
        - GA-N-RI-1P
        - GA-N-RI-2P
        - GA-N-RI-SBOX
        - GA-N-TF-1P
        - GA-N-TF-2P
        - GA-N-TF-SBOX
    decay: 0.8
    decay_coeff: 0.99
    llh_sample_runs: 3
    llh_sample_budget_coeff:  0.01
    llh_budget_coeff: 0.05
  HH-GA-N-E-SBOX-PSO-SA-N-RI:
    enabled: True
    description: Hyper heuristics - GA & PSO & SA
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - PSO
        - GA-N-E-SBOX
        - SA-N-RI
    decay: 0.8
    decay_coeff: 0.99
    llh_sample_runs: 3
    llh_sample_budget_coeff:  0.01
    llh_budget_coeff: 0.05
