# Optimizers configuration

  SA:
    enabled: True
    description: Simulated Annealing
    type: low
    optimizer: SA
    generator_comb: discrete
    generator_cont: continuous
    variator: n_exchange_adjacent
    initial_sample: True
    lb: null
    ub: null
    reheat: True
  DE:
    enabled: False
    description: Differential Evolution (Inspyred)
    type: low
    optimizer: DEA
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  ES:
    enabled: False
    description: Evoluation Strategy (Inspyred)
    type: low
    optimizer: ES
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA:
    enabled: False
    description: Genetic algorithm with parent selection, mutation, elitism
    type: low
    optimizer: GA
    generator_comb: discrete
    generator_cont: chromosome
    variator: n_exchange
    crossover: sbox
    initial_sample: False
    lb: null
    ub: null
    number_parents: 2
    number_children: 10
    parent_gene_similarity_threshold: 0.8
  PSO:
    enabled: False
    description: Particle swarm
    type: low
    optimizer: PSO
    generator_comb: continuous
    generator_cont: continuous
    initial_sample: False
    lb: 0
    ub: 4
  GA-HH:
    enabled: False
    description: Hyper heuristics
    type: hyper
    optimizer: HH
    low_level_selection_pool:
        - DE
        - ES
    decay: 0.5
    decay_coeff: 0.97
    llh_sample_runs: 3
    llh_sample_budget_coeff:  0.01
    llh_budget_coeff: 0.05

