# Problem configuration

  FSSP:
    enabled: True
    type: combinatorial
    description: Flow Shop Scheduling Problem
    benchmarks:
        taillard_20_5_i1.txt:
            enabled: False
        taillard_20_10_i1.txt:
            enabled: True
        taillard_50_10_i1.txt:
            enabled: False
        taillard_100_10_i1.txt:
            enabled: False
    lb: 0
    ub: nmax
    inertia_coeff: 0.4
    local_coeff: 2.1
    global_coeff: 2.1
  RASTRIGIN:
    enabled: True
    type: continuous
    description: Rastrigin
    lb: -5.12
    ub: 5.12
    inertia_coeff: 0.7
    local_coeff: 2.0
    global_coeff: 2.0
