# Problem configuration

  FSSP:
    enabled: False
    type: combinatorial
    generator: discrete
    description: Flow Shop Scheduling Problem
    benchmarks:
        taillard_20_5_i1.txt:
            enabled: False
        taillard_20_10_i1.txt:
            enabled: True
        taillard_50_10_i1.txt:
            enabled: False
        taillard_100_10_i1.txt:
            enabled: False
    lb: 0
    ub: nmax
  RASTRIGIN:
    enabled: True
    type: continuous
    generator: continuous
    description: Rastrigin
    lb: -5.12
    ub: 5.12
